### ISSUE TITLE
接続確認ダイアログを「x」ボタンで閉じると、接続アイコンが非活性のままになる

### ISSUE THREAD

**Issue by Hondarer** [kenzauros/rharbor#23]
接続確認ダイアログを「x」ボタンで閉じると、接続アイコンが非活性のままになる。
このシナリオでダイアログを閉じた際、IDialog.OnClose() が呼び出されず、ずっとダイアログ表示中の認識になっており、MainWindow.ShowConfirmationDialog() が戻ってこない。

DialogBehavior.Closed() に以下の処理を追加すると現象は解決しますが、解消方法はいくつかあるので、最適な対応かどうか確認したい。

```
       private void Closed(object sender, EventArgs e)
        {
            if (Content != null) // Window Close Button or Alt+F4 or etc.
            {
                var vm = Content as IDialog; // ADD
                vm.CloseWindow(); // ADD

                Content = null;
            }
        }
```

**Comment by kenzauros** [comment]
@Hondarer 回答遅れて申し訳ありませんでした。一応私としても最適解かどうかわかりませんが、いただいた案がシンプルかと思いますので #24 で修正しております。
