### ISSUE TITLE
RDPタブとSSHタブで設定するグループが共通であれば便利

### ISSUE THREAD

**Issue by norikazum** [kenzauros/rharbor#55]
（1.5.0にて）

SSHで設定できるグループと、RDPで設定できるグループがそれぞれ別なので個人的には共通のほうが便利だと思います。

**Comment by kenzauros** [comment]
ご要望ありがとうございます。
ご指摘の部分は接続のプロパティで「グループ名」のドロップダウンを開いたときの選択候補の話でしょうか？

**Comment by norikazum** [comment]
>ご指摘の部分は接続のプロパティで「グループ名」のドロップダウンを開いたときの選択候補の話でしょうか？
はい、ドロップダウンの選択候補です。

**Comment by kenzauros** [comment]
元々の RHarbor の用途を考えると RDP と SSH はグループが同じことも多そうですね。
私もそのほうが便利かなと思いますので、仕様変更します。
