### ISSUE TITLE
同名の接続情報に対して内容を変更して保存すると同名の別設定ができてしまう

### ISSUE THREAD

**Issue by norikazum** [kenzauros/rharbor#58]
①の内容を修正して、秘密鍵の設定を入れて保存すると②ができた。
![2021-04-21_22h25_33](https://user-images.githubusercontent.com/25143165/115561781-dd162980-a2f0-11eb-88f6-80180547391e.jpg)

**Comment by norikazum** [comment]
グループを変更しても、変更前と変更先に情報が残ってしまう。

**Comment by kenzauros** [comment]
編集ではなく複製ボタンを押していませんか？

**Comment by norikazum** [comment]
失礼しました。
複製ボタンを押していました。
