### ISSUE TITLE
SSH 接続追加パラメータが消える

### ISSUE THREAD

**Issue by hiratatsu04** [kenzauros/rharbor#71]
1つの接続先に追加パラメータを追加して、2つ目のものに設定を追加すると、1つ目のパラメータが消える（空欄に戻る）

<img width="390" alt="2023-03-20_17h17_40" src="https://user-images.githubusercontent.com/13930492/226286656-40518715-534b-455d-b39e-0280b6f64a41.png">

**Comment by kenzauros** [comment]
ご報告ありがとうございます。バグでした。修正します。

**Comment by hiratatsu04** [comment]
https://github.com/kenzauros/rharbor/pull/69#issuecomment-1475840212

で修正いただいたものでパラメータが消えないことを確認いたしました。

**Comment by hiratatsu04** [comment]
本件とは関係ないかもしれませんが、一度設定したパラメータを変更すると以下のエラーが発生します。
保存ボタンを押して設定完了できません。
キャンセルボタンを押して編集モードを終了すると、パラメータの変更は保存されていました。
ご確認よろしくお願いいたします。

```
The operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted.
```

**Comment by hiratatsu04** [comment]
上記は ssh の新規登録の際にも発生しました。
本エラーが出るため、新規の保存ができませんでした。
